# 生产环境：由 CD 流水线自动更新镜像 tag（GitOps 模式）
#   kustomize edit set image ghcr.io/zzz-blog/taskflow-devops/taskflow-api=ghcr.io/<owner>/taskflow-api:<sha>
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/zzz-blog/taskflow-devops/taskflow-api
  newName: ghcr.io/zzz-blog/taskflow-devops/taskflow-api
  newTag: e9f29d5
- name: ghcr.io/zzz-blog/taskflow-devops/taskflow-web
  newName: ghcr.io/zzz-blog/taskflow-devops/taskflow-web
  newTag: e9f29d5
